### PR TITLE
Strip ANSI control characters from build log output

### PR DESCRIPTION
**Pull request by sirreal**
Work in progress. Untested.

### CODE REVIEW

**Comment by dmsnell** [comment]
Did you consider converting them so we can get the colors through on the output?

**Comment by sirreal** [comment]
I did and I think that would be nice. I'm having trouble getting this running, so I just implemented this and was planning to come back when I have more time. I don't know whether this is working correctly.

**Comment by samouri** [comment]
i wish we had dserve for dserve

**Comment by samouri** [comment]
@dmsnell did you test it?

**Pull request merged**
